UPDATE BOOK_METADATA
SET STATUS = 'UNKNOWN'
WHERE ID IN (
    SELECT m.id
    FROM BOOK_METADATA m,
         BOOK_METADATA_PAGE p
    WHERE m.ID = p.BOOK_METADATA_ID
      AND m.THUMBNAIL IS NULL
      AND p.NUMBER = 0
      AND p.MEDIA_TYPE = 'image/webp');
